[IOS] Create Home Screen
vasyl-nadtochii/crypto_app_ios pull request #6
Opened 2022-12-06 16:59 UTC by zhenyapavlovsky

## What's new
1. Create UI for `Home screen`

## Issue

[Issue](https://trello.com/c/igDtwZY6)

## Screenshot

<img width="260" alt="Screenshot 2022-12-06 at 18 59 18" src="https://user-images.githubusercontent.com/99541081/205975009-2c342b62-32e0-4e26-a813-3ffb92fd9ffc.png">

2022-12-06 17:22 UTC, vasyl-nadtochii requested changes

2022-12-06 17:22 UTC, vasyl-nadtochii commented on Crypto_App_iOS/Flows/Screens/Home/HomeView.swift
> +                        bitcoinSection
please, remove this `vars` and create some dummy array of data. Then, using `ForEach` create list UI

2022-12-06 17:22 UTC, vasyl-nadtochii commented on Crypto_App_iOS/Flows/Screens/Home/HomeView.swift
> +
extra space

2022-12-06 19:07 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Flows/Screens/Home/HomeView.swift
> +
Done

2022-12-08 12:29 UTC, vasyl-nadtochii approved these changes

2022-12-08 12:29 UTC, vasyl-nadtochii commented on Crypto_App_iOS/Flows/Screens/Home/HomeView.swift
> +//    var bitcoinSection: some View {
why do we need to have that commented? If it's not needed, just remove that

2022-12-08 12:29 UTC, vasyl-nadtochii commented on Crypto_App_iOS/Flows/Screens/Home/Data.swift
> +    let sectionCoin = [
move this array to the `HomeViewModel`

2022-12-08 12:29 UTC, vasyl-nadtochii commented on Crypto_App_iOS/Resources/en.lproj/Localizable.strings
> +"bitcoin" = "Bitcoin";
I guess we don't need that more

2022-12-08 15:44 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Flows/Screens/Home/HomeView.swift
> +//    var bitcoinSection: some View {
Done

2022-12-08 15:52 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Flows/Screens/Home/Data.swift
> +    let sectionCoin = [
Done

2022-12-08 16:19 UTC, merged